[build-system]
requires = ["setuptools>=67.0"]
build-backend = "setuptools.build_meta"
[project]
name = "natural-retroduction"
version = "0.0.1"
authors = [
    {name="Machina Ratiocinatrix", email="machina.ratio@gmail.com"},
    {name="Alexander Fedotov", email="alex.fedotov@aol.com"}
]
description = "Natural retroduction"
readme = "README.md"
requires-python = ">=3.10"
classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
]

keywords = ["natural-retroduction"]

dependencies = [
    "pyyaml == 6.0.3"
]

[project.scripts]
natural-retroduction = "natural_retroduction.cli:run"

[project.urls]
"Homepage" = "https://github.com/natural-retroduction/natural-retroduction"
"Bug Tracker" = "https://github.com/natural-retroduction/natural-retroduction/issues"